version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: p@$$w0rd
      POSTGRES_USER: bookman
      POSTGRES_DB: bookman
    volumes:
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
#      - ./postgresql:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  bookman:
    build: code
    restart: always
    ports:
      - 5000:5000
#    volumes:
#      - ./code:/code
#    command: "sleep 100000"